<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>AeroColor.Sample</RootNamespace>
    <AssemblyName>AeroColor.Sample</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>AeroColor.Sample.App</StartupObject>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroColor\AeroColor.csproj" />
  </ItemGroup>
</Project>